services:
  catalogue:
    build: ./catalogue
    image: catalogue:1.0
    container_name: catalogue
    depends_on:
      - mongodb
  
  mongodb:
    build: ./mongodb
    image: mongodb:1.0
    container_name: mongodb

  frontend:
    build: ./frontend
    image: frontend:1.0
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue

networks:
  default:
    name: roboshop
    driver: bridge
    external: false
      