services:
  catalogue:
    build: ./catalogue
    image: subbukola541/catalogue:1.0
    container_name: catalogue
    depends_on:
      - mongodb

  user:
    build: ./user
    image: subbukola541/user:1.0
    container_name: user
    depends_on:
      - mongodb
      - redis

  cart:
    build: ./cart
    image: subbukola541/cart:1.0
    container_name: cart
    depends_on:
      - redis
      - catalogue
  
  shipping:
    build: ./shipping
    image: subbukola541/shipping:1.0
    container_name: shipping
    depends_on:
      - mysql
      - cart

  payment:
    build: ./payment
    image: subbukola541/payment:1.0
    container_name: payment
    depends_on:
      - rabbitmq
      - cart
      - user

  
  frontend:
    build: ./frontend
    image: subbukola541/frontend:1.0
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment

  
  mongodb:
    build: ./mongodb
    image: subbukola541/mongodb:1.0
    container_name: mongodb
    volumes:
      - mongodb:/data/db

  redis:
    #build: ./redis
    image: subbukola541/redis:7.0
    container_name: redis
    volumes:
      - redis:/data

  mysql:
    build: ./mysql
    image: subbukola541/mysql:1.0
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql

  rabbitmq:
    image: subbukola541/rabbitmq:3
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    container_name: rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq

networks:
  default:
    name: roboshop
    driver: bridge
    external: false

volumes:
  mongodb: 
  redis:
  mysql:
  rabbitmq:
      